cache:
  directories:
    - /var/cache/apt/archives/
  
language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
  - sudo apt-get update -qq
    
install: 
  - sudo apt-get -y install qt58base qt58declarative qt58quickcontrols2 qt58svg qt58webengine
  - source /opt/qt58/bin/qt58-env.sh

script:
  - mkdir -p ./appdir
  - wget -O quazip.zip "http://downloads.sourceforge.net/project/quazip/quazip/0.4.4/quazip-0.4.4.zip?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fquazip%2F&ts=1328389079&use_mirror=heanet"
  - unzip quazip.zip
  - cd quazip-0.4.4
  - sed -i 's/SHARED/STATIC/g' quazip/CMakeLists.txt
  - cmake .
  - make
  - sudo make install
  - git clone -b develop https://github.com/lirios/fluid
  - cd fluid
  - git submodule update --init
  - mkdir build
  - cd build
  - qmake LIRI_INSTALL_PREFIX=/usr ..
  - make -j4
  - sudo make install
  - sudo make INSTALL_ROOT=../../appdir install ; sudo chown -R $USER ../../appdir ; find ../../appdir/
  - cd ../../
  - git clone https://github.com/tim-sueberkrueb/slime-engine
  - cd slime-engine
  - qmake PREFIX=/usr
  - make -j4
  - sudo make install
  - sudo make INSTALL_ROOT=../appdir install ; sudo chown -R $USER ../appdir ; find ../appdir/
  - cd ../
  - mkdir build
  - cd build
  - qmake LIRI_INSTALL_PREFIX=/usr CONFIG+=QTWEBENGINE_ENABLED ..
  - make -j4
  - sudo make INSTALL_ROOT=../appdir install ; sudo chown -R $USER ../appdir ; find ../appdir/
  - cd ../
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
